version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: utss
      POSTGRES_PASSWORD: AaBbCc12345@
      PGDATA: /data/postgres
      POSTGRES_DB: TaskManagementDb
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  web:
    container_name: taskmanagementapi
    build:
      context: ./TaskManagementApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5259
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=TaskManagementDb
      - DB_USER=utss
      - DB_PASSWORD=AaBbCc12345@
    ports:
      - "5259:5259"
    depends_on:
      - db
    networks:
      - db
    restart: unless-stopped
  frontend:
    container_name: task_management
    build:
      context: ./task-manager-app
    ports:
      - "4200:4000"
    depends_on:
      - web
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db: