services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: utss
      POSTGRES_PASSWORD: AaBbCc12345@
      PGDATA: /data/postgres
      POSTGRES_DB: TaskManagementDb
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: